import { Minus, Plus } from "lucide-react";
import type { CityDashboardView, CityJobId } from "../../domain/cityPresentation";
import { CityIcon } from "./cityIcons";

const jobIcons: Record<CityJobId, string> = { farmers: "Grape", woodcutters: "Trees", quarrymen: "Hammer", miners: "Pickaxe" };

export default function AssignmentPanel({ view, canMutate, onAllocate }: { view: CityDashboardView; canMutate: boolean; onAllocate: (role: CityJobId, amount: number) => void }) {
  return <section data-testid="assignment-panel" className="order-3 xl:col-start-3 xl:row-start-1 bg-[#18110b] border border-[#45301f] rounded-xl p-5 shadow-lg space-y-4">
    <div className="pb-4 border-b border-[#3c291a]"><h3 className="text-xs font-bold tracking-widest text-[#caa050] uppercase font-serif mb-1">Affectations</h3><p className="text-[11px] text-[#a89078]">Citoyens libres et répartition des rôles de production.</p></div>
    <div className="bg-[#100a06] p-3 rounded-lg border border-[#302014]"><div className="flex justify-between text-[11px] font-semibold text-[#dfdbc7] mb-1"><span>Immigration</span><span className="text-amber-500 font-mono">{view.totalCitizens} / {view.maxCitizens}</span></div><div className="w-full h-2 bg-[#1a110a] rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-[#86592e] to-[#caa050]" style={{ width: `${view.totalCitizens >= view.maxCitizens ? 0 : view.citizenGrowthProgress}%` }} /></div></div>
    {view.unassignedCitizens > 0 && <div className="p-2.5 bg-amber-950/20 border border-amber-500/30 rounded-lg text-xs text-[#ebd7a0]">⚠️ {view.unassignedCitizens} citoyen(s) disponible(s)</div>}
    <div className="space-y-3">{view.jobs.map((job) => <div key={job.id} className="bg-[#120a06] p-3 rounded-lg border border-[#45301f] flex items-center justify-between gap-4"><div className="flex items-center gap-2.5"><div className="w-9 h-9 rounded-lg bg-[#2c1d12] flex items-center justify-center"><CityIcon name={jobIcons[job.id]} /></div><div><h4 className="text-xs font-bold text-[#dfdbc7] font-serif">{job.label}</h4><span className="text-[9.5px] text-[#8f8376] font-mono">{job.buildingLabel} Niv. {job.buildingLevel}</span></div></div><div className="flex items-center gap-2.5 font-mono"><button type="button" aria-label={`Retirer un ${job.label}`} onClick={() => onAllocate(job.id, -1)} disabled={!canMutate || !job.canRemove} className="min-h-11 min-w-11 rounded bg-[#2c1d12] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#caa050] disabled:opacity-30"><Minus className="w-3.5 h-3.5" /></button><span className="w-6 text-center text-sm font-bold">{job.count}</span><button type="button" aria-label={`Ajouter un ${job.label}`} onClick={() => onAllocate(job.id, 1)} disabled={!canMutate || !job.canAdd} className="min-h-11 min-w-11 rounded bg-[#2c1d12] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#caa050] disabled:opacity-30"><Plus className="w-3.5 h-3.5" /></button></div></div>)}</div>
  </section>;
}
